#############################################################################
# Makefile for building: FMS
# Generated by qmake (3.1) (Qt 6.5.2)
# Project:  FMS.pro
# Template: subdirs
# Command: D:\QT\6.5.2\msvc2019_64\bin\qmake.exe -o Makefile FMS.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\QT\6.5.2\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\QT\6.5.2\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\QT\6.5.2\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-IDE \
		sub-Plugin


sub-IDE-qmake_all:  FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	cd IDE\ && $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && $(MAKE) -f Makefile qmake_all
sub-IDE: $(MAKEFILE) FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-IDE-make_first-ordered: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-IDE-make_first: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-IDE-all-ordered: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-IDE-all: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-IDE-clean-ordered: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-IDE-clean: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-IDE-distclean-ordered: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-IDE-distclean: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-IDE-install_subtargets-ordered: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-IDE-install_subtargets: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-IDE-uninstall_subtargets-ordered: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-IDE-uninstall_subtargets: FORCE
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Plugin-qmake_all: sub-IDE-qmake_all FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	cd Plugin\ && $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && $(MAKE) -f Makefile qmake_all
sub-Plugin: $(MAKEFILE) FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Plugin-make_first-ordered: sub-IDE-make_first-ordered  FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Plugin-make_first: FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Plugin-all-ordered: sub-IDE-all-ordered  FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Plugin-all: FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Plugin-clean-ordered: sub-IDE-clean-ordered  FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Plugin-clean: FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Plugin-distclean-ordered: sub-IDE-distclean-ordered  FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Plugin-distclean: FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Plugin-install_subtargets-ordered: sub-IDE-install_subtargets-ordered  FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Plugin-install_subtargets: FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Plugin-uninstall_subtargets-ordered: sub-IDE-uninstall_subtargets-ordered  FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Plugin-uninstall_subtargets: FORCE
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: FMS.pro D:\QT\6.5.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf D:\QT\6.5.2\msvc2019_64\mkspecs\features\spec_pre.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\common\windows-desktop.conf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\qconfig.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_grpc.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_grpc_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\qt_functions.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\qt_config.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\common\msvc-version.conf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\toolchain.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\default_pre.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\resolve_config.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\default_post.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\qtquickcompiler.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\entrypoint.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\precompile_header.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\warn_on.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\qmake_use.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\file_copies.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\win32\windows.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\testcase_targets.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\exceptions.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\yacc.prf \
		D:\QT\6.5.2\msvc2019_64\mkspecs\features\lex.prf \
		FMS.pro
	$(QMAKE) -o Makefile FMS.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
D:\QT\6.5.2\msvc2019_64\mkspecs\features\spec_pre.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\common\windows-desktop.conf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\common\windows-vulkan.conf:
D:\QT\6.5.2\msvc2019_64\mkspecs\common\msvc-desktop.conf:
D:\QT\6.5.2\msvc2019_64\mkspecs\qconfig.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_grpc.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_grpc_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\qt_functions.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\qt_config.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\spec_post.prf:
.qmake.stash:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\exclusive_builds.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\common\msvc-version.conf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\toolchain.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\default_pre.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\win32\default_pre.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\resolve_config.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\default_post.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\qtquickcompiler.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\entrypoint.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\precompile_header.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\warn_on.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\qmake_use.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\file_copies.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\win32\windows.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\testcase_targets.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\exceptions.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\yacc.prf:
D:\QT\6.5.2\msvc2019_64\mkspecs\features\lex.prf:
FMS.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile FMS.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: sub-IDE-qmake_all sub-Plugin-qmake_all FORCE

make_first: sub-IDE-make_first-ordered sub-Plugin-make_first-ordered  FORCE
all: sub-IDE-all-ordered sub-Plugin-all-ordered  FORCE
clean: sub-IDE-clean-ordered sub-Plugin-clean-ordered  FORCE
distclean: sub-IDE-distclean-ordered sub-Plugin-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-IDE-install_subtargets-ordered sub-Plugin-install_subtargets-ordered FORCE
uninstall_subtargets: sub-IDE-uninstall_subtargets-ordered sub-Plugin-uninstall_subtargets-ordered FORCE

sub-IDE-debug_ordered:
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Plugin-debug_ordered: sub-IDE-debug_ordered 
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-IDE-debug_ordered sub-Plugin-debug_ordered

sub-IDE-release_ordered:
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Plugin-release_ordered: sub-IDE-release_ordered 
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-IDE-release_ordered sub-Plugin-release_ordered

sub-IDE-check_ordered:
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Plugin-check_ordered: sub-IDE-check_ordered 
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-IDE-check_ordered sub-Plugin-check_ordered

sub-IDE-benchmark_ordered:
	@if not exist IDE\ mkdir IDE\ & if not exist IDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\IDE\IDE.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Plugin-benchmark_ordered: sub-IDE-benchmark_ordered 
	@if not exist Plugin\ mkdir Plugin\ & if not exist Plugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Plugin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProject\FireMonkeyStudio\Plugin\Plugin.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-IDE-benchmark_ordered sub-Plugin-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

