#ifndef PLUGIN_CPPBASE_GLOBAL_H
#define PLUGIN_CPPBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_CPPBASE_LIBRARY)
#  define PLUGIN_CPPBASE_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_CPPBASE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_CPPBASE_GLOBAL_H
