
#ifndef PLUGIN_UIXEDITOR_GLOBAL_H
#define PLUGIN_UIXEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_UIXEDITOR_LIBRARY)
#  define PLUGIN_UIXEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_UIXEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_UIXEDITOR_GLOBAL_H
