
#ifndef PLUGIN_CPPBASIC_GLOBAL_H
#define PLUGIN_CPPBASIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_CPPBASIC_LIBRARY)
#  define PLUGIN_CPPBASIC_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_CPPBASIC_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_CPPBASIC_GLOBAL_H
